{
  "config": {
    "abort": {
      "already_configured": "[%key:common::config_flow::abort::already_configured_account%]",
      "already_in_progress": "[%key:common::config_flow::abort::already_in_progress%]",
      "authorize_url_timeout": "[%key:common::config_flow::abort::oauth2_authorize_url_timeout%]",
      "cloud_not_enabled": "Please make sure you run Home Assistant with `{default_config}` enabled in your configuration.yaml.",
      "missing_configuration": "[%key:common::config_flow::abort::oauth2_missing_configuration%]",
      "no_url_available": "[%key:common::config_flow::abort::oauth2_no_url_available%]",
      "oauth_error": "[%key:common::config_flow::abort::oauth2_error%]",
      "oauth_failed": "[%key:common::config_flow::abort::oauth2_failed%]",
      "oauth_timeout": "[%key:common::config_flow::abort::oauth2_timeout%]",
      "oauth_unauthorized": "[%key:common::config_flow::abort::oauth2_unauthorized%]",
      "reauth_successful": "[%key:common::config_flow::abort::reauth_successful%]",
      "user_rejected_authorize": "[%key:common::config_flow::abort::oauth2_user_rejected_authorize%]",
      "wrong_account": "You are authenticated with a different account than the one set up. Please authenticate with the configured account."
    },
    "create_entry": {
      "default": "[%key:common::config_flow::create_entry::authenticated%]"
    },
    "step": {
      "oauth_discovery": {
        "description": "Home Assistant has found an Aladdin Connect device on your network. Press **Submit** to continue setting up Aladdin Connect."
      },
      "pick_implementation": {
        "title": "[%key:common::config_flow::title::oauth2_pick_implementation%]"
      },
      "reauth_confirm": {
        "description": "Aladdin Connect needs to re-authenticate your account",
        "title": "[%key:common::config_flow::title::reauth%]"
      }
    }
  }
}
